FROM public.ecr.aws/docker/library/node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

COPY .env .env

RUN npm ci

RUN npm audit fix

COPY . .
COPY .env .env
# RUN npm run migrate:latest

EXPOSE 80

CMD ["npm", "run", "start:prod"]
